"""Add diagnostic sessions

Revision ID: 9c0c5e6b215a
Revises: 1a6c52f05449
Create Date: 2026-10-04 17:45:09.198746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0c5e6b215a'
down_revision: Union[str, None] = '1a6c52f05449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_sessions',
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('initial_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_diagnostic_sessions_status'),
    sa.CheckConstraint('revision > 0', name='ck_diagnostic_sessions_revision'),
    sa.PrimaryKeyConstraint('organisation_id', 'session_id')
    )
    op.create_index('ix_diagnostic_sessions_org_created', 'diagnostic_sessions', ['organisation_id', 'created_at'], unique=False)
    op.create_table('session_observations',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_unknown', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_unknown AND answer IS NULL) OR (NOT is_unknown AND answer IS NOT NULL AND length(btrim(answer)) > 0)', name='ck_session_observations_answer'),
    sa.ForeignKeyConstraint(['organisation_id', 'session_id'], ['diagnostic_sessions.organisation_id', 'diagnostic_sessions.session_id'], name='fk_session_observations_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index('ix_session_observations_session_created', 'session_observations', ['organisation_id', 'session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_observations_session_created', table_name='session_observations')
    op.drop_table('session_observations')
    op.drop_index('ix_diagnostic_sessions_org_created', table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    # ### end Alembic commands ###
