"""Create historical cases

Revision ID: ae2f331c0d0a
Revises: 
Create Date: 2026-10-03 22:13:02.501988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2f331c0d0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_cases',
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('customer_description', sa.Text(), nullable=False),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('resolution_text', sa.Text(), nullable=True),
    sa.Column('parts_replaced', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('stored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('organisation_id', 'case_id')
    )
    op.create_index('ix_historical_cases_org_family', 'historical_cases', ['organisation_id', 'equipment_family'], unique=False)
    op.create_index('ix_historical_cases_org_type', 'historical_cases', ['organisation_id', 'equipment_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_cases_org_type', table_name='historical_cases')
    op.drop_index('ix_historical_cases_org_family', table_name='historical_cases')
    op.drop_table('historical_cases')
    # ### end Alembic commands ###
